dashboard_currencies_action:
  path: /currencies
  controller: currency_converter_bundle.action.dashboard
  methods: [ GET ]

list_currencies_action:
  path: /currencies/list/{page}
  controller: currency_converter_bundle.action.list
  methods: [ GET ]
  defaults:
    page: 1

update_currencies_action:
  path: /currencies/update
  controller: currency_converter_bundle.action.update_currencies
  methods: [ POST ]
