parameters:
  currency_converter_bundle.translation_domain: CurrencyConverterBundle
  # Class actions:
  currency_converter_bundle.action.dashboard.class: Bundles\CurrencyConverterBundle\Action\DashboardAction
  currency_converter_bundle.action.list.class: Bundles\CurrencyConverterBundle\Action\ListAction
  currency_converter_bundle.action.add.class: Bundles\CurrencyConverterBundle\Action\AddAction
  currency_converter_bundle.action.edit.class: Bundles\CurrencyConverterBundle\Action\EditAction
  currency_converter_bundle.action.convert.class: Bundles\CurrencyConverterBundle\Action\ConvertAction

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Actions
  currency_converter_bundle.action.dashboard:
    class: '%currency_converter_bundle.action.dashboard.class%'
  currency_converter_bundle.action.list:
    class: '%currency_converter_bundle.action.list.class%'
  currency_converter_bundle.action.add:
    class: '%currency_converter_bundle.action.add.class%'
  currency_converter_bundle.action.edit:
    class: '%currency_converter_bundle.action.edit.class%'
  currency_converter_bundle.action.convert:
    class: '%currency_converter_bundle.action.convert.class%'
